//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.user_member {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtuser_id;
		protected global::System.Web.UI.WebControls.TextBox txtmember_id;
		protected global::System.Web.UI.WebControls.TextBox txtmember_stuid;
		protected global::System.Web.UI.WebControls.TextBox txtmember_balance;
		protected global::System.Web.UI.WebControls.TextBox txtmember_level;
		protected global::System.Web.UI.WebControls.TextBox txtmember_activities_sn;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
