//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.banner {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtbanner_title;
		protected global::System.Web.UI.WebControls.TextBox txtbanner_abstract;
		protected global::System.Web.UI.WebControls.TextBox txtbanner_link;
		protected global::System.Web.UI.WebControls.TextBox txtbanner_img;
		protected global::System.Web.UI.WebControls.TextBox txtbanner_state;
		protected global::System.Web.UI.WebControls.TextBox txtbanner_posterid;
		protected global::System.Web.UI.WebControls.TextBox txtbanner_postdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
