//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.banner {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblbanner_id;
	protected global::System.Web.UI.WebControls.Label lblbanner_title;
	protected global::System.Web.UI.WebControls.Label lblbanner_abstract;
	protected global::System.Web.UI.WebControls.Label lblbanner_link;
	protected global::System.Web.UI.WebControls.Label lblbanner_img;
	protected global::System.Web.UI.WebControls.Label lblbanner_state;
	protected global::System.Web.UI.WebControls.Label lblbanner_posterid;
	protected global::System.Web.UI.WebControls.Label lblbanner_postdate;


       
    }
}
