//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.news {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblnews_id;
	protected global::System.Web.UI.WebControls.Label lblnews_createtime;
	protected global::System.Web.UI.WebControls.Label lblnews_posterid;
	protected global::System.Web.UI.WebControls.Label lblnews_title;
	protected global::System.Web.UI.WebControls.Label lblnews_class;
	protected global::System.Web.UI.WebControls.Label lblnews_abstract;
	protected global::System.Web.UI.WebControls.Label lblnews_content;
	protected global::System.Web.UI.WebControls.Label lblnews_readnum;
	protected global::System.Web.UI.WebControls.Label lblnews_state;


       
    }
}
