//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.user_ider {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtider_id;
		protected global::System.Web.UI.WebControls.TextBox txtdept_id;
		protected global::System.Web.UI.WebControls.TextBox txtrole_id;
		protected global::System.Web.UI.WebControls.TextBox txtrole_starttime;
		protected global::System.Web.UI.WebControls.TextBox txtrole_endtime;
		protected global::System.Web.UI.WebControls.TextBox txtider_balance;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
