//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.notice_email {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtemail_sn;
		protected global::System.Web.UI.WebControls.TextBox txtemail_class;
		protected global::System.Web.UI.WebControls.CheckBox chkemail_theme;
		protected global::System.Web.UI.WebControls.TextBox txtemail_content;
		protected global::System.Web.UI.WebControls.TextBox txtemail_doc_id;
		protected global::System.Web.UI.WebControls.TextBox txtemail_postitme;
		protected global::System.Web.UI.WebControls.TextBox txtemail_settime;
		protected global::System.Web.UI.WebControls.TextBox txtsender_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
