//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.notice_email {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblemail_sn;
	protected global::System.Web.UI.WebControls.Label lblemail_class;
	protected global::System.Web.UI.WebControls.Label lblemail_theme;
	protected global::System.Web.UI.WebControls.Label lblemail_content;
	protected global::System.Web.UI.WebControls.Label lblemail_doc_id;
	protected global::System.Web.UI.WebControls.Label lblemail_postitme;
	protected global::System.Web.UI.WebControls.Label lblemail_settime;
	protected global::System.Web.UI.WebControls.Label lblsender_id;


       
    }
}
