//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.activities_record {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblact_sn;
		protected global::System.Web.UI.WebControls.TextBox txtact_appleytime;
		protected global::System.Web.UI.WebControls.TextBox txtact_id;
		protected global::System.Web.UI.WebControls.TextBox txtmember_id;
		protected global::System.Web.UI.WebControls.TextBox txtstate;
		protected global::System.Web.UI.WebControls.TextBox txtchecker_id;
		protected global::System.Web.UI.WebControls.TextBox txtchecker_date;
		protected global::System.Web.UI.WebControls.TextBox txtmember_evaluate;
		protected global::System.Web.UI.WebControls.TextBox txtreply_id;
		protected global::System.Web.UI.WebControls.TextBox txtreply_date;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
