//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.activities_record {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblact_sn;
	protected global::System.Web.UI.WebControls.Label lblact_appleytime;
	protected global::System.Web.UI.WebControls.Label lblact_id;
	protected global::System.Web.UI.WebControls.Label lblmember_id;
	protected global::System.Web.UI.WebControls.Label lblstate;
	protected global::System.Web.UI.WebControls.Label lblchecker_id;
	protected global::System.Web.UI.WebControls.Label lblchecker_date;
	protected global::System.Web.UI.WebControls.Label lblmember_evaluate;
	protected global::System.Web.UI.WebControls.Label lblreply_id;
	protected global::System.Web.UI.WebControls.Label lblreply_date;


       
    }
}
