//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.activities {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtact_class;
		protected global::System.Web.UI.WebControls.TextBox txtact_name;
		protected global::System.Web.UI.WebControls.TextBox txtact_applytime;
		protected global::System.Web.UI.WebControls.TextBox txtact_applysettime;
		protected global::System.Web.UI.WebControls.TextBox txtact_startime;
		protected global::System.Web.UI.WebControls.TextBox txtact_endtime;
		protected global::System.Web.UI.WebControls.TextBox txtposter_id;
		protected global::System.Web.UI.WebControls.TextBox txtdoc_id;
		protected global::System.Web.UI.WebControls.TextBox txtact_abstract;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
