//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.activities {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblact_id;
	protected global::System.Web.UI.WebControls.Label lblact_class;
	protected global::System.Web.UI.WebControls.Label lblact_name;
	protected global::System.Web.UI.WebControls.Label lblact_applytime;
	protected global::System.Web.UI.WebControls.Label lblact_applysettime;
	protected global::System.Web.UI.WebControls.Label lblact_startime;
	protected global::System.Web.UI.WebControls.Label lblact_endtime;
	protected global::System.Web.UI.WebControls.Label lblposter_id;
	protected global::System.Web.UI.WebControls.Label lbldoc_id;
	protected global::System.Web.UI.WebControls.Label lblact_abstract;


       
    }
}
