//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.user_info {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lbluser_id;
		protected global::System.Web.UI.WebControls.TextBox txtuser_realname;
		protected global::System.Web.UI.WebControls.TextBox txtuser_stuid;
		protected global::System.Web.UI.WebControls.TextBox txtuser_school;
		protected global::System.Web.UI.WebControls.TextBox txtuser_major;
		protected global::System.Web.UI.WebControls.TextBox txtuser_sex;
		protected global::System.Web.UI.WebControls.TextBox txtuser_phone;
		protected global::System.Web.UI.WebControls.TextBox txtuser_email;
		protected global::System.Web.UI.WebControls.TextBox txtuser_qq;
		protected global::System.Web.UI.WebControls.TextBox txtuser_birthday;
		protected global::System.Web.UI.WebControls.TextBox txtuser_home;
		protected global::System.Web.UI.WebControls.TextBox txtuser_nation;
		protected global::System.Web.UI.WebControls.TextBox txtuser_politices;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
