//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.user_info {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluser_id;
	protected global::System.Web.UI.WebControls.Label lbluser_realname;
	protected global::System.Web.UI.WebControls.Label lbluser_stuid;
	protected global::System.Web.UI.WebControls.Label lbluser_school;
	protected global::System.Web.UI.WebControls.Label lbluser_major;
	protected global::System.Web.UI.WebControls.Label lbluser_sex;
	protected global::System.Web.UI.WebControls.Label lbluser_phone;
	protected global::System.Web.UI.WebControls.Label lbluser_email;
	protected global::System.Web.UI.WebControls.Label lbluser_qq;
	protected global::System.Web.UI.WebControls.Label lbluser_birthday;
	protected global::System.Web.UI.WebControls.Label lbluser_home;
	protected global::System.Web.UI.WebControls.Label lbluser_nation;
	protected global::System.Web.UI.WebControls.Label lbluser_politices;


       
    }
}
