//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.apply_ider {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblapply_sn;
		protected global::System.Web.UI.WebControls.TextBox txtuser_id;
		protected global::System.Web.UI.WebControls.TextBox txtpassword;
		protected global::System.Web.UI.WebControls.TextBox txtfirstChoice;
		protected global::System.Web.UI.WebControls.TextBox txtsecondChoice;
		protected global::System.Web.UI.WebControls.CheckBox chkadjusted;
		protected global::System.Web.UI.WebControls.TextBox txtapply_phote;
		protected global::System.Web.UI.WebControls.TextBox txtapply_introduce;
		protected global::System.Web.UI.WebControls.TextBox txtapply_hobby;
		protected global::System.Web.UI.WebControls.TextBox txtapply_advantage;
		protected global::System.Web.UI.WebControls.TextBox txtapply_workplan;
		protected global::System.Web.UI.WebControls.TextBox txtapply_time;
		protected global::System.Web.UI.WebControls.TextBox txtapply_state;
		protected global::System.Web.UI.WebControls.TextBox txtapply_remark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
