//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.apply_ider {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblapply_sn;
	protected global::System.Web.UI.WebControls.Label lbluser_id;
	protected global::System.Web.UI.WebControls.Label lblpassword;
	protected global::System.Web.UI.WebControls.Label lblfirstChoice;
	protected global::System.Web.UI.WebControls.Label lblsecondChoice;
	protected global::System.Web.UI.WebControls.Label lbladjusted;
	protected global::System.Web.UI.WebControls.Label lblapply_phote;
	protected global::System.Web.UI.WebControls.Label lblapply_introduce;
	protected global::System.Web.UI.WebControls.Label lblapply_hobby;
	protected global::System.Web.UI.WebControls.Label lblapply_advantage;
	protected global::System.Web.UI.WebControls.Label lblapply_workplan;
	protected global::System.Web.UI.WebControls.Label lblapply_time;
	protected global::System.Web.UI.WebControls.Label lblapply_state;
	protected global::System.Web.UI.WebControls.Label lblapply_remark;


       
    }
}
