//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.user_account {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lbluser_id;
	protected global::System.Web.UI.WebControls.Label lbluser_pwd;
	protected global::System.Web.UI.WebControls.Label lbluser_nickname;
	protected global::System.Web.UI.WebControls.Label lbluser_registerdate;
	protected global::System.Web.UI.WebControls.Label lbluser_lastlogindate;
	protected global::System.Web.UI.WebControls.Label lbluser_loginnum;
	protected global::System.Web.UI.WebControls.Label lbluser_email;
	protected global::System.Web.UI.WebControls.Label lbluser_photo;
	protected global::System.Web.UI.WebControls.Label lbluser_pwd_que;
	protected global::System.Web.UI.WebControls.Label lbluser_pwd_ans;
	protected global::System.Web.UI.WebControls.Label lbluser_class;


       
    }
}
